name: CI
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:19.9.0-alpine
      # this is the user that CI uses, which is needed to generate files within the repo directory
      options: --user 1001

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
